### ISSUE TITLE
ImportError: cannot import name dummy_reporter

### ISSUE THREAD

**Issue by fraoustin** [abakan/ablog#97]
when run ablog, i have

> fraoustin@debian:~/ablog$ ablog build
> Traceback (most recent call last):
>   File "/usr/local/bin/ablog", line 7, in <module>
>     from ablog.commands import ablog_main
>   File "/usr/local/lib/python2.7/dist-packages/ablog/__init__.py", line 5, in <module>
>     from .blog import Blog, CONFIG
>   File "/usr/local/lib/python2.7/dist-packages/ablog/blog.py", line 21, in <module>
>     from sphinx.environment import dummy_reporter
> ImportError: cannot import name dummy_reporter

ablog version 0.8.4
sphinx 1.7.0

**Comment by nabobalis** [comment]
There is  currently several issues with Ablog and the lastest release of Sphinx. Hopefully I will get a new release soon.

**Comment by emacsway** [comment]
:+1:

**Comment by fraoustin** [comment]
ok it's work with sphinx version 1.5.2, In your setup.py it's necessary to identify this version
`
install_requires=['Werkzeug', 'Sphinx==1.5.2', 'alabaster', 'invoke', 'python-dateutil']
`
thank you

**Comment by nabobalis** [comment]
A new version of Ablog (v0.9.0) is out at [this repo.](https://github.com/sunpy/ablog)

This issue should be fixed now but we made it explicitly support Sphinx`>=1.6`.
